apiVersion: apps/v1
kind: Deployment
metadata:
  name: transliterator
  labels:
    app: transliterator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transliterator
  template:
    metadata:
      labels:
        app: transliterator
    spec:
      containers:
        - name: transliterator
          image: ttl.sh/transliterator-1761557140-16821:1h
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
