apiVersion: v1
kind: Service
metadata:
  name: transliterator
  labels:
    app: transliterator
spec:
  selector:
    app: transliterator
  ports:
    - name: http
      port: 80
      targetPort: 8080
