apiVersion: apps/v1
kind: Deployment
metadata:
  name: slugger
  labels:
    app: slugger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slugger
  template:
    metadata:
      labels:
        app: slugger
    spec:
      containers:
        - name: slugger
          image: ttl.sh/slugger-1761555347-25423:1h
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
